/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import StudentuBalai.Balas;
import StudentuBalai.DB;

/**
 *
 * @author Vaidos
 */
public class DB_gui extends javax.swing.JFrame {
    public static boolean kalba = true;
    DB db;   
    Balas balas;
    TableModel model;
    String data;
    int studentoBalas;
    String paaiskinimas;
    int studentoNr;
    int ID;
    int i;
    String infoMessage1 = "Duomenys sėkmingai atnaujinti!";
    String warningMessage1 = "Neteisingai įvesti duomenys!";
    String infoMessage2 = "Duomenys sėkmingai ištrinti!";
    String informacija = "Informacija";
    String klaida = "Klaida";  

    /**
     * Creates new form DB_gui
     */
    public DB_gui() {
        initComponents();
        showDBTable();
        visiStudentai();
    }
    
    public void showDBTable(){
        ArrayList<Balas> balasList = balas.balasList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[5];
        for(int  i = 0; i < balasList.size(); i++){
            row[0] = balasList.get(i).getId();
            row[1] = balasList.get(i).getData();
            row[2] = balasList.get(i).getBalai();
            row[3] = balasList.get(i).getPaaiskinimas();
            row[4] = balasList.get(i).getStudentas();
            model.addRow(row);
        }
    }
    public ArrayList<Balas> filtredBalasList(){
        ArrayList<Balas> filtredBalasList = new ArrayList<Balas>();
        try{
            Connection conn = db.getConnection();
            String sql = "SELECT * FROM balas WHERE (irasymo_data BETWEEN ?  AND ?) AND (studentas = ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date sqlData1 = new Date(date.parse(jTextField5.getText()).getTime());
            Date sqlData2 = new Date(date.parse(jTextField6.getText()).getTime());
            stmt.setDate(1, sqlData1);
            stmt.setDate(2, sqlData2);
            stmt.setInt(3, Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            ResultSet rs = stmt.executeQuery();      
            while( rs.next()){
                balas = new Balas(rs.getInt("balo_id"), rs.getDate("irasymo_data"), rs.getInt("balai"), rs.getString("paaiskinimas"), rs.getInt("studentas"));
                filtredBalasList.add(balas);
            }    
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return filtredBalasList;
    }
    
    public void showFiltredDBTable(){
        ArrayList<Balas> filtredBalasList = filtredBalasList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[5];
        for(int  i = 0; i < filtredBalasList.size(); i++){
            row[0] = filtredBalasList.get(i).getId();
            row[1] = filtredBalasList.get(i).getData();
            row[2] = filtredBalasList.get(i).getBalai();
            row[3] = filtredBalasList.get(i).getPaaiskinimas();
            row[4] = filtredBalasList.get(i).getStudentas();
            model.addRow(row);
        }
    }
    
    public void visiStudentai(){
        try{
            Connection conn = db.getConnection();
            String sql = "SELECT * FROM studentas";
            Statement stmt = (Statement) conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql); 
            while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
            }
        }catch(Exception ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Balai", "Paaiskinimas", "Studentas"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("DB_gui.jTable1.columnModel.title0")); // NOI18N
            jTable1.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("DB_gui.jTable1.columnModel.title1")); // NOI18N
            jTable1.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("DB_gui.jTable1.columnModel.title2")); // NOI18N
            jTable1.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("DB_gui.jTable1.columnModel.title3")); // NOI18N
            jTable1.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("DB_gui.jTable1.columnModel.title4")); // NOI18N
        }

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("DB_gui.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("DB_gui.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("DB_gui.jLabel3.text")); // NOI18N

        jLabel4.setText(bundle.getString("DB_gui.jLabel4.text")); // NOI18N

        jButton1.setBackground(new java.awt.Color(196, 93, 93));
        jButton1.setText(bundle.getString("DB_gui.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(bundle.getString("DB_gui.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(bundle.getString("DB_gui.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText(bundle.getString("DB_gui.jLabel5.text")); // NOI18N

        jLabel6.setText(bundle.getString("DB_gui.jLabel6.text")); // NOI18N

        jLabel7.setText(bundle.getString("DB_gui.jLabel7.text")); // NOI18N

        jButton4.setText(bundle.getString("DB_gui.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu2.setText(bundle.getString("DB_gui.jMenu2.text")); // NOI18N

        jMenuItem1.setText(bundle.getString("DB_gui.jMenuItem1.text")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText(bundle.getString("DB_gui.jMenuItem2.text")); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText(bundle.getString("DB_gui.jMenuItem3.text")); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText(bundle.getString("DB_gui.jMenu3.text")); // NOI18N

        jMenuItem4.setText(bundle.getString("DB_gui.jMenuItem4.text")); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText(bundle.getString("DB_gui.jMenuItem5.text")); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(26, 26, 26))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jButton4))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(16, 16, 16)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Prideti_studenta prideti =  new Prideti_studenta(kalba);
        prideti.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Prideti_grupe prideti =  new Prideti_grupe(kalba);
        prideti.setVisible(true);
        //kalba = prideti.kalba;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Prideti_bala prideti =  new Prideti_bala(kalba);
        prideti.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        i = jTable1.getSelectedRow();
        model = jTable1.getModel();
        jTextField1.setText(model.getValueAt(i, 4).toString());
        jTextField2.setText(model.getValueAt(i, 2).toString());
        jTextField3.setText(model.getValueAt(i, 1).toString());
        jTextField4.setText(model.getValueAt(i, 3).toString()); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        showDBTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            ID = Integer.parseInt(model.getValueAt(i, 0).toString());
            balas.deleteBalas(ID);
            JOptionPane.showMessageDialog(this, infoMessage2 , informacija, JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            data =jTextField3.getText();
            studentoBalas = Integer.parseInt(jTextField2.getText());
            paaiskinimas = jTextField4.getText();
            studentoNr = Integer.parseInt(jTextField1.getText());
            ID = Integer.parseInt(model.getValueAt(i, 0).toString());
            balas.updateBalas(data, studentoBalas, paaiskinimas, studentoNr, ID);
            JOptionPane.showMessageDialog(this, infoMessage1, informacija, JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, warningMessage1, klaida, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        showFiltredDBTable(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Locale currentLocale1 = new Locale("en", "GB");
        ResourceBundle messages1 = ResourceBundle.getBundle("pkg7laboras/Bundle", currentLocale1);
        jMenuItem5.setText(messages1.getString("angluKalba"));
        jButton4.setText(messages1.getString("filtras"));
        jMenuItem4.setText(messages1.getString("lietuviuKalba"));
        jLabel7.setText(messages1.getString("dataIki"));
        jLabel6.setText(messages1.getString("dataNuo"));
        jLabel5.setText(messages1.getString("studentas1"));
        jLabel1.setText(messages1.getString("studentas2"));
        jMenu3.setText(messages1.getString("kalba"));
        jButton3.setText(messages1.getString("atnaujinti"));
        jMenuItem3.setText(messages1.getString("pridetiBalus"));
        jButton2.setText(messages1.getString("koreguotiIrasa"));
        jButton1.setText(messages1.getString("istrintiIrasa"));
        jMenuItem2.setText(messages1.getString("pridetiStudenta"));
        jLabel4.setText(messages1.getString("paaiskinimas"));
        jLabel3.setText(messages1.getString("data"));
        jMenuItem1.setText(messages1.getString("pridetiGrupe"));
        jLabel2.setText(messages1.getString("balai"));
        jMenu2.setText(messages1.getString("pildyti"));
        jTable1.getColumnModel().getColumn(0).setHeaderValue(messages1.getString("title0"));
        jTable1.getColumnModel().getColumn(1).setHeaderValue(messages1.getString("title1"));
        jTable1.getColumnModel().getColumn(2).setHeaderValue(messages1.getString("title2"));
        jTable1.getColumnModel().getColumn(3).setHeaderValue(messages1.getString("title3"));
        jTable1.getColumnModel().getColumn(4).setHeaderValue(messages1.getString("title4"));
        infoMessage1 = messages1.getString("infoMessage1");
        warningMessage1 = messages1.getString("warningMessage1");
        infoMessage2 = messages1.getString("infoMessage2");
        informacija = messages1.getString("informacija");
        klaida = messages1.getString("klaida");
        kalba=false;
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Locale currentLocale1 = new Locale("lt", "LT");
        ResourceBundle messages1 = ResourceBundle.getBundle("pkg7laboras/Bundle", currentLocale1);
        jMenuItem5.setText(messages1.getString("angluKalba"));
        jButton4.setText(messages1.getString("filtras"));
        jMenuItem4.setText(messages1.getString("lietuviuKalba"));
        jLabel7.setText(messages1.getString("dataIki"));
        jLabel6.setText(messages1.getString("dataNuo"));
        jLabel5.setText(messages1.getString("studentas1"));
        jLabel1.setText(messages1.getString("studentas2"));
        jMenu3.setText(messages1.getString("kalba"));
        jButton3.setText(messages1.getString("atnaujinti"));
        jMenuItem3.setText(messages1.getString("pridetiBalus"));
        jButton2.setText(messages1.getString("koreguotiIrasa"));
        jButton1.setText(messages1.getString("istrintiIrasa"));
        jMenuItem2.setText(messages1.getString("pridetiStudenta"));
        jLabel4.setText(messages1.getString("paaiskinimas"));
        jLabel3.setText(messages1.getString("data"));
        jMenuItem1.setText(messages1.getString("pridetiGrupe"));
        jLabel2.setText(messages1.getString("balai"));
        jMenu2.setText(messages1.getString("pildyti"));
        jTable1.getColumnModel().getColumn(0).setHeaderValue(messages1.getString("title0"));
        jTable1.getColumnModel().getColumn(1).setHeaderValue(messages1.getString("title1"));
        jTable1.getColumnModel().getColumn(2).setHeaderValue(messages1.getString("title2"));
        jTable1.getColumnModel().getColumn(3).setHeaderValue(messages1.getString("title3"));
        jTable1.getColumnModel().getColumn(4).setHeaderValue(messages1.getString("title4"));
        infoMessage1 = messages1.getString("infoMessage1");
        warningMessage1 = messages1.getString("warningMessage1");
        infoMessage2 = messages1.getString("infoMessage2");
        informacija = messages1.getString("informacija");
        klaida = messages1.getString("klaida");
        kalba=true;
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DB_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DB_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DB_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DB_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DB_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
