/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import StudentuBalai.DB;
import StudentuBalai.Studentas;
import static GUI.Prideti_grupe.kalba;

/**
 *
 * @author Vaidos
 */
public class Prideti_studenta extends javax.swing.JFrame {
    static boolean kalba = true;
    DB db;
    Studentas studentas;
    Integer nr; 
    String vardas;
    String pavarde;
    String grupe;
    String infoMessage = "Duomenys sėkmingai įrašyti!";
    String warningMessage = "Neteisingai įvesti duomenys!";
    String informacija = "Informacija";
    String klaida = "Klaida";  
    /**
     * Creates new form Prideti_studenta
     */
    public Prideti_studenta(boolean kalbosPasirinkimas) {
        initComponents();
        grupesToComboBox();
        kalba = kalbosPasirinkimas;
        if(kalbosPasirinkimas) {
            ltKalba();
        }else {
            enKalba();
        }
    }
   
    public void ltKalba () {
        Locale currentLocale1 = new Locale("lt", "LT");
        ResourceBundle messages1 = ResourceBundle.getBundle("pkg7laboras/Bundle", currentLocale1);
        jLabel2.setText(messages1.getString("vardas"));
        jLabel1.setText(messages1.getString("studentoNr"));
        jButton2.setText(messages1.getString("atsaukti2"));
        jButton1.setText(messages1.getString("issaugoti2"));
        jLabel4.setText(messages1.getString("grupe"));
        jLabel3.setText(messages1.getString("pavarde"));
        warningMessage = messages1.getString("warningMessage");
        infoMessage = messages1.getString("infoMessage");
        informacija = messages1.getString("informacija");
        klaida = messages1.getString("klaida");
        kalba=true;
    }
    
    public void enKalba () {
        Locale currentLocale1 = new Locale("en", "GB");
        ResourceBundle messages1 = ResourceBundle.getBundle("pkg7laboras/Bundle", currentLocale1);
        jLabel2.setText(messages1.getString("vardas"));
        jLabel1.setText(messages1.getString("studentoNr"));
        jButton2.setText(messages1.getString("atsaukti2"));
        jButton1.setText(messages1.getString("issaugoti2"));
        jLabel4.setText(messages1.getString("grupe"));
        jLabel3.setText(messages1.getString("pavarde"));
        warningMessage = messages1.getString("warningMessage");
        infoMessage = messages1.getString("infoMessage");
        informacija = messages1.getString("informacija");
        klaida = messages1.getString("klaida");
        kalba=false;
    }
    
    public void grupesToComboBox(){
        try{
            Connection conn = db.getConnection();
            String sql = "SELECT * FROM grupe";
            Statement stmt = (Statement) conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql); 
            while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
        }
        }catch(Exception ex) {
            ex.printStackTrace();
        }
    }       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pkg7laboras/Bundle"); // NOI18N
        setTitle(bundle.getString("Prideti_studenta.title")); // NOI18N

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        jLabel1.setText(bundle1.getString("Prideti_studenta.jLabel1.text_1")); // NOI18N

        jLabel2.setText(bundle1.getString("Prideti_studenta.jLabel2.text_1")); // NOI18N

        jLabel3.setText(bundle1.getString("Prideti_studenta.jLabel3.text_1")); // NOI18N

        jLabel4.setText(bundle1.getString("Prideti_studenta.jLabel4.text_1")); // NOI18N

        jButton1.setText(bundle1.getString("Prideti_studenta.jButton1.text_1")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(bundle1.getString("Prideti_studenta.jButton2.text_1")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jComboBox1, 0, 133, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            nr = parseInt(jTextField1.getText());
            vardas = jTextField2.getText();
            pavarde = jTextField3.getText();
            grupe = String.valueOf(jComboBox1.getSelectedItem());
            studentas.insertStudentas(nr, vardas, pavarde, grupe);
            JOptionPane.showMessageDialog(this, infoMessage, informacija, JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, warningMessage, klaida, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prideti_studenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prideti_studenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prideti_studenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prideti_studenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prideti_studenta(kalba).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
